import { StyleSheet } from "react-native";
import { INPUT_COLOR, PRIMARY_COLOR, SECONDARY_COLOR } from './commons/constants';

export const styles = StyleSheet.create({
    title: {
        color: SECONDARY_COLOR,
        fontSize: 25,
        fontWeight: 'bold',
        paddingHorizontal: 30,
        paddingVertical: 30
    },
    containerBody: {
        backgroundColor: SECONDARY_COLOR,
        borderTopLeftRadius:30,
        borderTopRightRadius:30,
        paddingHorizontal:45,
        paddingTop:40
    },
    titlePrincipal:{
        fontSize:17,
        fontWeight:'bold'
    },
    titleSecondary:{
        fontSize:15,
        marginTop:10
    },
    input:{
        backgroundColor:INPUT_COLOR,
        borderRadius:5,
        paddingHorizontal:20,
        marginVertical:7
    },
    containerInput:{
        marginVertical:10
    },
    containerButton:{
        backgroundColor:PRIMARY_COLOR,
        paddingVertical:15,
        borderRadius:5,

    },
    textBotton:{
        color:SECONDARY_COLOR,
        textAlign:'center',
        fontSize:15,
        fontWeight:'bold'
    },
    icon:{
        position:'absolute',
        right:10,
        top:75
    },
    textRedirect:{
        marginTop:20,
        color:PRIMARY_COLOR,
        fontSize:15,
        fontWeight:'bold',
        textAlign:'center'
    },
    containerCard:{
        //flexDirection:'row',
        flex:1,
        width:150,
        justifyContent:'center',
        alignItems:'center',
        padding:10,
        borderWidth:1,
        borderColor:SECONDARY_COLOR,
        borderStyle:'solid',
        //borderRadius:5,
        shadowColor:'#ccc',
        shadowOpacity:0.23,
        shadowRadius:1,
        elevation:2,
        marginBottom:15
    },
    titleProdcut:{
        fontSize:15,
        fontWeight:'bold'
    },
    imageProduct:{
        width:60,
        height:60
    },
    containerIcon:{
        flex:1,
        //backgroundColor:'red',
        alignItems:'flex-end'
    },
    containerModal:{
        flex:1,
        backgroundColor:'rgba(0,0,0,0.5)',
        justifyContent:'center',
        alignItems:'center',
    },
    contentModal:{
        padding:20,
        backgroundColor:SECONDARY_COLOR,
        borderRadius:10
    },
    headerModal:{
        flexDirection:'row',
        borderBottomColor:'#ccc',
        borderBottomWidth:1,
        padding:10
    },
    titleModal:{
        fontSize:20,
        fontWeight:'bold'
    },
    imageModal:{
        width:200,
        height:200
    },
    containerImage:{
        alignItems:'center'
    },
    containerQuantity:{
       // marginTop:10,
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center'
    },
    buttonQuantity:{
        height:50,
        width:50,
        backgroundColor:PRIMARY_COLOR,
        borderRadius:30,
        justifyContent:'center',
        alignItems:'center',
        margin:15
    },
    buttonTextQuantity:{
        color:SECONDARY_COLOR,
        fontSize:16,
        fontWeight:'bold',
    },
    textQuantity:{
        fontSize:15,
        fontWeight:'bold',
    },
    buttonAddCar:{
        backgroundColor:PRIMARY_COLOR,
        alignItems:'center',
        paddingVertical:10,
        borderRadius:5,
        marginTop:10
    },
    buttonTextAddCar:{
        color:SECONDARY_COLOR,
        fontWeight:'bold'
    },
    textStock:{  
        color:'red',
        textAlign:'center',
        marginTop:10,
        fontSize:20,
        fontWeight:'bold',
    },
    headerHome:{
        flexDirection:'row',
        alignItems:'center'
    },
    textIconCar:{
        backgroundColor:SECONDARY_COLOR,
        paddingHorizontal:5,
        borderRadius:20,
        fontSize:12,
        fontWeight:'bold'
    },
    headerTeable:{
        flexDirection:'row',
        justifyContent:'space-between',
        paddingVertical:8,
        alignItems:'center',
        borderBottomWidth:1,
        borderBottomColor:'#ccc'
    },
    headerDescription:{
        flexDirection:'row',
        justifyContent:'space-between',
        flex:1,
        alignItems:'center'
    },
    textHeaderTable:{
        fontSize:15,
        fontWeight:'bold',
        color:'#000'
    },
    containerTotal:{
        marginVertical:1,
        alignItems:'flex-end',
        paddingHorizontal:10
    },
    textTotal:{
        fontSize:18,
        fontWeight:'bold'
    }
})